"""
Django settings for analiz_klientiv project.

Generated by "django-admin startproject" using Django 4.2.0.
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-your-secret-key-here"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "bankruptcy",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "analiz_klientiv.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "analiz_klientiv.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "analiz_klientiv",
        "USER": "analiz_user",
        "PASSWORD": "analiz_password",
        "HOST": "localhost",
        "PORT": "5432",
        "CONN_MAX_AGE": 0,    # Негайно закривати з'єднання після використання
        "OPTIONS": {
            "connect_timeout": 10,
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "uk-ua"

TIME_ZONE = "Europe/Kyiv"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {asctime} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "bankruptcy_monitor.log",
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "loggers": {
        "bankruptcy.file_monitor": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": True,
        },
        "bankruptcy.apps": {
            "handlers": ["file", "console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

# УЛЬТРА ПРОДУКТИВНІСТЬ - максимальні налаштування для найвищої швидкості
SEARCH_MAX_WORKERS = 15     # УЛЬТРА: 15 воркерів для ультра швидкості пошуку
SEARCH_BATCH_SIZE = 300     # УЛЬТРА: максимальні батчі для найвищої ефективності
RESOLUTION_MAX_WORKERS = 15  # УЛЬТРА: 15 воркерів для ультра швидкого витягування резолютивних частин
RESOLUTION_BATCH_SIZE = 400  # УЛЬТРА: максимальні батчі для найвищої ефективності
RESOLUTION_SUB_BATCH_SIZE = 50  # УЛЬТРА: максимальні суб-батчі для найшвидшої обробки  
RESOLUTION_MINI_BATCH_SIZE = 30 # УЛЬТРА: максимальні мінібатчі для максимального паралелізму
COURT_DECISIONS_DB_DIR = BASE_DIR / "data" / "search_databases"
TEMP_DIR = "/tmp/resolution_temp"
RESOLUTION_DOWNLOAD_TIMEOUT = 45  # Збільшено як в SR_AI
REQUEST_DELAY = 0.05  # УЛЬТРА: мінімальна затримка для максимальної швидкості

# Налаштування швидкого пошуку судових рішень (адаптація SR_AI)
USE_FAST_COURT_SEARCH = True  # Використовувати швидкий точний пошук
FAST_SEARCH_MAX_WORKERS = 15  # УЛЬТРА: 15 воркерів для ультра швидкості пошуку
FAST_SEARCH_BATCH_SIZE = 300  # УЛЬТРА: максимальні батчі для найвищої ефективності

# Налаштування автоматичної оптимізації індексів
INDEX_OPTIMIZATION_MIN_RECORDS = 1000      # Мінімальна кількість записів для тригера оптимізації
INDEX_OPTIMIZATION_INTERVAL_HOURS = 24     # Мінімальний інтервал між оптимізаціями (годин)

# УЛЬТРА ПРОДУКТИВНІСТЬ - найвищі ліміти для найшвидшої обробки
MAX_TOTAL_DB_CONNECTIONS = 75              # УЛЬТРА: 75 загальних з'єднань для ультра швидкості
MAX_CONCURRENT_THREADS = 35                # УЛЬТРА: 35 одночасних потоків для максимального паралелізму
DB_CONNECTION_POOL_SIZE = 45               # УЛЬТРА: максимальний пул з'єднань
DB_CONNECTION_POOL_MAX_OVERFLOW = 30       # УЛЬТРА: максимальний резерв додаткових з'єднань

# Налаштування пошуку судових рішень
USE_FAST_COURT_SEARCH = False              # Відключаємо SQLite швидкий пошук, використовуємо PostgreSQL