# Generated by Django 5.2.6 on 2025-09-09 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edrpou', models.CharField(max_length=20, unique=True, verbose_name='Код ЄДРПОУ')),
                ('name', models.TextField(verbose_name='Назва підприємства')),
            ],
            options={
                'verbose_name': 'Підприємство',
                'verbose_name_plural': 'Підприємства',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Назва суду')),
            ],
            options={
                'verbose_name': 'Суд',
                'verbose_name_plural': 'Суди',
                'db_table': 'court',
            },
        ),
        migrations.CreateModel(
            name='BankruptcyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='Порядковий номер')),
                ('date', models.DateField(verbose_name='Дата провадження')),
                ('type', models.TextField(verbose_name='Тип провадження')),
                ('case_number', models.CharField(max_length=50, verbose_name='Номер справи')),
                ('start_date_auc', models.DateField(blank=True, null=True, verbose_name='Дата початку аукціону')),
                ('end_date_auc', models.DateField(blank=True, null=True, verbose_name='Дата закінчення аукціону')),
                ('end_registration_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення реєстрації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankruptcy_cases', to='bankruptcy.company', verbose_name='Підприємство')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankruptcy_cases', to='bankruptcy.court', verbose_name='Суд')),
            ],
            options={
                'verbose_name': 'Справа про банкрутство',
                'verbose_name_plural': 'Справи про банкрутство',
                'db_table': 'bankruptcy_case',
                'ordering': ['-number'],
                'indexes': [models.Index(fields=['date'], name='bankruptcy__date_c8a39b_idx'), models.Index(fields=['case_number'], name='bankruptcy__case_nu_bbbfe3_idx'), models.Index(fields=['number'], name='bankruptcy__number_f2bb19_idx')],
            },
        ),
    ]
