# Generated by Django 5.2.6 on 2025-09-09 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0001_initial'),
    ]

    operations = [
    ]
