# Generated by Django 5.2.6 on 2025-09-09 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0002_rename_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код категорії справи')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії справи')),
            ],
            options={
                'verbose_name': 'Категорія справи',
                'verbose_name_plural': 'Категорії справ',
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код інстанції')),
                ('name', models.CharField(max_length=255, verbose_name='Назва інстанції')),
            ],
            options={
                'verbose_name': 'Інстанція',
                'verbose_name_plural': 'Інстанції',
            },
        ),
        migrations.CreateModel(
            name='JudgmentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код форми судового рішення')),
                ('name', models.CharField(max_length=255, verbose_name='Назва форми судового рішення')),
            ],
            options={
                'verbose_name': 'Форма судового рішення',
                'verbose_name_plural': 'Форми судових рішень',
            },
        ),
        migrations.CreateModel(
            name='JusticeKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код виду судочинства')),
                ('name', models.CharField(max_length=255, verbose_name='Назва виду судочинства')),
            ],
            options={
                'verbose_name': 'Вид судочинства',
                'verbose_name_plural': 'Види судочинства',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код регіону')),
                ('name', models.CharField(max_length=255, verbose_name='Назва регіону')),
            ],
            options={
                'verbose_name': 'Регіон',
                'verbose_name_plural': 'Регіони',
            },
        ),
        migrations.CreateModel(
            name='CourtDecisionDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True, verbose_name='Рік')),
                ('csv_file_path', models.CharField(blank=True, max_length=512, verbose_name='Шлях до CSV файлу')),
                ('csv_file_size', models.BigIntegerField(default=0, verbose_name='Розмір CSV файлу')),
                ('csv_last_modified', models.DateTimeField(blank=True, null=True, verbose_name='Дата зміни CSV')),
                ('documents_count', models.IntegerField(default=0, verbose_name='Кількість документів')),
                ('import_status', models.CharField(choices=[('pending', 'Очікування'), ('importing', 'Імпорт'), ('completed', 'Завершено'), ('failed', 'Помилка')], default='pending', max_length=20, verbose_name='Статус імпорту')),
                ('import_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Початок імпорту')),
                ('import_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення імпорту')),
                ('import_error_message', models.TextField(blank=True, verbose_name='Повідомлення про помилку')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'База даних судових рішень',
                'verbose_name_plural': 'Бази даних судових рішень',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CourtDecisionImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file_path', models.CharField(max_length=512, verbose_name='Шлях до CSV')),
                ('csv_records_total', models.IntegerField(default=0, verbose_name='Всього записів у CSV')),
                ('records_imported', models.IntegerField(default=0, verbose_name='Імпортовано записів')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Оновлено записів')),
                ('records_skipped', models.IntegerField(default=0, verbose_name='Пропущено записів')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Початок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення')),
                ('is_successful', models.BooleanField(default=False, verbose_name='Успішно')),
                ('error_message', models.TextField(blank=True, verbose_name='Помилка')),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='bankruptcy.courtdecisiondatabase', verbose_name='База даних')),
            ],
            options={
                'verbose_name': 'Лог імпорту судових рішень',
                'verbose_name_plural': 'Логи імпорту судових рішень',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CourtDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='ID документа')),
                ('court_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Код суду')),
                ('judgment_code', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Код форми рішення')),
                ('justice_kind', models.CharField(blank=True, db_index=True, max_length=10, verbose_name='Код виду судочинства')),
                ('category_code', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='Код категорії справи')),
                ('cause_num', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Номер справи')),
                ('adjudication_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата рішення')),
                ('receipt_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата надходження')),
                ('judge', models.CharField(blank=True, max_length=500, verbose_name='Суддя')),
                ('doc_url', models.URLField(blank=True, max_length=1000, verbose_name='URL документа')),
                ('status', models.CharField(blank=True, max_length=10, verbose_name='Статус')),
                ('date_publ', models.DateTimeField(blank=True, null=True, verbose_name='Дата публікації')),
                ('court_name', models.CharField(blank=True, max_length=500, verbose_name='Назва суду')),
                ('judgment_name', models.CharField(blank=True, max_length=200, verbose_name='Назва форми рішення')),
                ('justice_kind_name', models.CharField(blank=True, max_length=200, verbose_name='Вид судочинства')),
                ('category_name', models.CharField(blank=True, max_length=200, verbose_name='Категорія справи')),
                ('resolution_text', models.TextField(blank=True, verbose_name='Резолютивна частина')),
                ('import_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата імпорту')),
                ('bankruptcy_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_decisions', to='bankruptcy.bankruptcycase', verbose_name='Справа про банкрутство')),
                ('database_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankruptcy.courtdecisiondatabase', verbose_name='База даних джерело')),
            ],
            options={
                'verbose_name': 'Судове рішення',
                'verbose_name_plural': 'Судові рішення',
                'ordering': ['-adjudication_date', '-import_date'],
            },
        ),
        migrations.AddIndex(
            model_name='courtdecision',
            index=models.Index(fields=['cause_num'], name='bankruptcy__cause_n_1eb86e_idx'),
        ),
        migrations.AddIndex(
            model_name='courtdecision',
            index=models.Index(fields=['court_code', 'adjudication_date'], name='bankruptcy__court_c_67c170_idx'),
        ),
        migrations.AddIndex(
            model_name='courtdecision',
            index=models.Index(fields=['justice_kind', 'category_code'], name='bankruptcy__justice_2e95bb_idx'),
        ),
        migrations.AddIndex(
            model_name='courtdecision',
            index=models.Index(fields=['doc_id'], name='bankruptcy__doc_id_175ee4_idx'),
        ),
    ]