# Generated by Django 5.2.6 on 2025-09-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0003_auto_20250909_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtDecisionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('general', 'Загальна статистика'), ('yearly', 'Статистика по роках'), ('courts', 'Статистика по судах'), ('categories', 'Статистика по категоріях'), ('justice_kinds', 'Статистика по видах судочинства'), ('recent', 'Останні рішення')], db_index=True, max_length=20, verbose_name='Тип статистики')),
                ('stat_key', models.CharField(blank=True, db_index=True, help_text='Додатковий ключ для групування (наприклад, рік, код суду)', max_length=100, verbose_name='Ключ статистики')),
                ('stat_data', models.JSONField(help_text='JSON з статистичними даними', verbose_name='Дані статистики')),
                ('records_count', models.BigIntegerField(default=0, help_text='Загальна кількість записів, на основі яких розрахована статистика', verbose_name='Кількість записів')),
                ('calculation_time', models.DurationField(blank=True, help_text='Час, потрачений на розрахунок статистики', null=True, verbose_name='Час розрахунку')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Оновлено')),
                ('cache_expires_at', models.DateTimeField(blank=True, help_text='Після цього часу статистика буде перерахована', null=True, verbose_name='Кеш діє до')),
                ('is_valid', models.BooleanField(default=True, help_text='False, якщо статистика потребує оновлення', verbose_name='Кеш валідний')),
            ],
            options={
                'verbose_name': 'Статистика судових рішень',
                'verbose_name_plural': 'Статистики судових рішень',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='bankruptcycase',
            new_name='bankruptcy__date_5c3e99_idx',
            old_name='bankruptcy__date_c8a39b_idx',
        ),
        migrations.RenameIndex(
            model_name='bankruptcycase',
            new_name='bankruptcy__case_nu_bc4a07_idx',
            old_name='bankruptcy__case_nu_bbbfe3_idx',
        ),
        migrations.RenameIndex(
            model_name='bankruptcycase',
            new_name='bankruptcy__number_6c880b_idx',
            old_name='bankruptcy__number_f2bb19_idx',
        ),
        migrations.AlterModelTable(
            name='bankruptcycase',
            table=None,
        ),
        migrations.AlterModelTable(
            name='company',
            table='bankruptcy_company',
        ),
        migrations.AlterModelTable(
            name='court',
            table='bankruptcy_court',
        ),
        migrations.AddIndex(
            model_name='courtdecisionstatistics',
            index=models.Index(fields=['stat_type', 'stat_key'], name='bankruptcy__stat_ty_2897d1_idx'),
        ),
        migrations.AddIndex(
            model_name='courtdecisionstatistics',
            index=models.Index(fields=['stat_type', 'is_valid', 'cache_expires_at'], name='bankruptcy__stat_ty_64edd0_idx'),
        ),
        migrations.AddIndex(
            model_name='courtdecisionstatistics',
            index=models.Index(fields=['is_valid', 'updated_at'], name='bankruptcy__is_vali_f388c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='courtdecisionstatistics',
            constraint=models.UniqueConstraint(fields=('stat_type', 'stat_key'), name='unique_stat_type_key'),
        ),
    ]
