# Generated by Django 5.2.6 on 2025-09-10 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0004_add_court_decision_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackedBankruptcyCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('suspended', 'Призупинена'), ('archived', 'Архівована')], default='active', max_length=20, verbose_name='Статус відстеження')),
                ('search_decisions_status', models.CharField(choices=[('pending', 'Очікування'), ('running', 'Виконується'), ('completed', 'Завершено'), ('failed', 'Помилка')], default='pending', max_length=20, verbose_name='Статус пошуку рішень')),
                ('search_decisions_found', models.IntegerField(default=0, verbose_name='Знайдено рішень')),
                ('search_decisions_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Пошук завершено')),
                ('priority', models.IntegerField(default=0, help_text='Вищий номер = вищий пріоритет', verbose_name='Пріоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('bankruptcy_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_cases', to='bankruptcy.bankruptcycase', verbose_name='Справа про банкрутство')),
            ],
            options={
                'verbose_name': 'Відстежувана справа банкрутства',
                'verbose_name_plural': 'Відстежувані справи банкрутства',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackedCourtDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.CharField(max_length=255, verbose_name='ID документа')),
                ('court_code', models.CharField(blank=True, max_length=100, verbose_name='Код суду')),
                ('judgment_code', models.CharField(blank=True, max_length=100, verbose_name='Код рішення')),
                ('justice_kind', models.CharField(blank=True, max_length=100, verbose_name='Вид судочинства')),
                ('category_code', models.CharField(blank=True, max_length=100, verbose_name='Код категорії')),
                ('cause_num', models.CharField(blank=True, max_length=255, verbose_name='Номер справи')),
                ('adjudication_date', models.CharField(blank=True, max_length=50, verbose_name='Дата рішення')),
                ('receipt_date', models.CharField(blank=True, max_length=50, verbose_name='Дата надходження')),
                ('judge', models.CharField(blank=True, max_length=500, verbose_name='Суддя')),
                ('doc_url', models.URLField(blank=True, verbose_name='URL документа')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Статус')),
                ('date_publ', models.CharField(blank=True, max_length=50, verbose_name='Дата публікації')),
                ('database_source', models.CharField(blank=True, max_length=100, verbose_name='База даних')),
                ('court_name', models.CharField(blank=True, max_length=500, verbose_name='Назва суду')),
                ('judgment_name', models.CharField(blank=True, max_length=200, verbose_name='Назва рішення')),
                ('justice_kind_name', models.CharField(blank=True, max_length=200, verbose_name='Назва виду судочинства')),
                ('category_name', models.CharField(blank=True, max_length=200, verbose_name='Назва категорії')),
                ('resolution_text', models.TextField(blank=True, verbose_name='Резолютивна частина')),
                ('found_at', models.DateTimeField(auto_now_add=True, verbose_name='Знайдено')),
                ('tracked_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_court_decisions', to='bankruptcy.trackedbankruptcycase', verbose_name='Відстежувана справа')),
            ],
            options={
                'verbose_name': 'Відстежене судове рішення',
                'verbose_name_plural': 'Відстежені судові рішення',
                'ordering': ['-found_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trackedbankruptcycase',
            index=models.Index(fields=['status', 'priority'], name='bankruptcy__status_f98254_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedbankruptcycase',
            index=models.Index(fields=['search_decisions_status'], name='bankruptcy__search__464ace_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedbankruptcycase',
            index=models.Index(fields=['-created_at'], name='bankruptcy__created_e2ad54_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackedbankruptcycase',
            unique_together={('bankruptcy_case',)},
        ),
        migrations.AddIndex(
            model_name='trackedcourtdecision',
            index=models.Index(fields=['doc_id'], name='bankruptcy__doc_id_9c7f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedcourtdecision',
            index=models.Index(fields=['cause_num'], name='bankruptcy__cause_n_2de66e_idx'),
        ),
        migrations.AddIndex(
            model_name='trackedcourtdecision',
            index=models.Index(fields=['adjudication_date'], name='bankruptcy__adjudic_c3888d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackedcourtdecision',
            unique_together={('tracked_case', 'doc_id')},
        ),
    ]
