# Generated by Django 5.2.6 on 2025-09-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0005_auto_20250910_1713'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='causecategory',
            table='bankruptcy_cause_categories',
        ),
        migrations.AlterModelTable(
            name='instance',
            table='bankruptcy_instances',
        ),
        migrations.AlterModelTable(
            name='judgmentform',
            table='bankruptcy_judgment_forms',
        ),
        migrations.AlterModelTable(
            name='justicekind',
            table='bankruptcy_justice_kinds',
        ),
        migrations.CreateModel(
            name='MonitoringStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(choices=[('search_progress', 'Прогрес пошуку судових рішень'), ('extraction_progress', 'Прогрес витягування резолютивних частин'), ('general_stats', 'Загальна статистика')], max_length=50, verbose_name='Тип статистики')),
                ('total_cases', models.IntegerField(default=0, verbose_name='Загальна кількість справ')),
                ('cases_with_decisions', models.IntegerField(default=0, verbose_name='Справи з рішеннями')),
                ('total_decisions', models.IntegerField(default=0, verbose_name='Загальна кількість рішень')),
                ('decisions_with_resolutions', models.IntegerField(default=0, verbose_name='Рішення з резолютивними частинами')),
                ('currently_processing', models.BooleanField(default=False, verbose_name='В обробці зараз')),
                ('processing_type', models.CharField(blank=True, max_length=100, verbose_name='Тип поточної обробки')),
                ('processed_count', models.IntegerField(default=0, verbose_name='Оброблено за поточний цикл')),
                ('total_to_process', models.IntegerField(default=0, verbose_name='Загально до обробки')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
                ('last_search_run', models.DateTimeField(blank=True, null=True, verbose_name='Останній запуск пошуку')),
                ('last_extraction_run', models.DateTimeField(blank=True, null=True, verbose_name='Останнє витягування резолютивних частин')),
                ('additional_data', models.JSONField(blank=True, default=dict, verbose_name='Додаткові дані')),
            ],
            options={
                'verbose_name': 'Статистика моніторингу',
                'verbose_name_plural': 'Статистика моніторингу',
                'db_table': 'bankruptcy_monitoring_statistics',
                'unique_together': {('stat_type',)},
            },
        ),
    ]
