# Generated by Django 5.2.6 on 2025-09-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0006_alter_causecategory_table_alter_instance_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringstatistics',
            name='decisions_without_rtf',
            field=models.IntegerField(default=0, verbose_name='Рішення без RTF файлів'),
        ),
    ]
