# Generated by Django 5.2.6 on 2025-09-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0007_monitoringstatistics_decisions_without_rtf'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemProcessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('court_search', 'Пошук судових рішень'), ('resolution_extraction', 'Витягування резолютивних частин'), ('file_monitoring', 'Моніторинг файлів')], max_length=50, unique=True, verbose_name='Тип процесу')),
                ('status', models.CharField(choices=[('idle', 'Очікування'), ('running', 'Виконується'), ('forced_running', 'Примусово запущений'), ('paused', 'Призупинений'), ('stopped', 'Зупинений'), ('error', 'Помилка')], default='idle', max_length=20, verbose_name='Статус процесу')),
                ('is_forced', models.BooleanField(default=False, verbose_name='Примусовий режим')),
                ('force_stop_others', models.BooleanField(default=False, verbose_name='Зупинити інші процеси')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Час запуску')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Час завершення')),
                ('progress_current', models.IntegerField(default=0, verbose_name='Поточний прогрес')),
                ('progress_total', models.IntegerField(default=0, verbose_name='Загальна кількість')),
                ('last_message', models.TextField(blank=True, verbose_name='Останнє повідомлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Управління процесом',
                'verbose_name_plural': 'Управління процесами',
                'db_table': 'bankruptcy_system_process_control',
            },
        ),
    ]
