# Generated by Django 5.2.6 on 2025-09-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0008_systemprocesscontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedcourtdecision',
            name='has_trigger_words',
            field=models.BooleanField(default=False, help_text='Чи містить резолютивна частина тригерні слова для мовної моделі', verbose_name='Має тригерні слова'),
        ),
        migrations.AddField(
            model_name='trackedcourtdecision',
            name='is_critical_decision',
            field=models.BooleanField(default=False, help_text='Чи містить критичні тригери для особливої уваги мовної моделі', verbose_name='Критичне рішення'),
        ),
        migrations.AddField(
            model_name='trackedcourtdecision',
            name='trigger_types',
            field=models.JSONField(blank=True, default=list, help_text='Типи тригерів: resolution, judgment_type, critical', verbose_name='Типи тригерів'),
        ),
        migrations.AddField(
            model_name='trackedcourtdecision',
            name='trigger_words_found',
            field=models.JSONField(blank=True, default=list, help_text='Список знайдених тригерних слів', verbose_name='Знайдені тригерні слова'),
        ),
    ]
