# Generated by Django 5.2.6 on 2025-09-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0009_trackedcourtdecision_has_trigger_words_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedcourtdecision',
            name='resolution_extracted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата витягування резолютивної частини'),
        ),
    ]
