# Generated by Django 5.2.6 on 2025-09-15 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0010_add_resolution_extracted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=500, verbose_name='Назва кредитора')),
                ('normalized_name', models.CharField(db_index=True, help_text='Назва без ТОВ, ПАТ тощо для групування', max_length=500, verbose_name='Нормалізована назва')),
                ('total_cases', models.PositiveIntegerField(default=0, verbose_name='Кількість справ')),
                ('total_amount_1st_queue', models.FloatField(default=0.0, verbose_name='Загальна сума 1 черга')),
                ('total_amount_2nd_queue', models.FloatField(default=0.0, verbose_name='Загальна сума 2 черга')),
                ('total_amount_3rd_queue', models.FloatField(default=0.0, verbose_name='Загальна сума 3 черга')),
                ('total_amount_4th_queue', models.FloatField(default=0.0, verbose_name='Загальна сума 4 черга')),
                ('total_amount_5th_queue', models.FloatField(default=0.0, verbose_name='Загальна сума 5 черга')),
                ('total_amount_6th_queue', models.FloatField(default=0.0, verbose_name='Загальна сума 6 черга')),
                ('total_amount_all', models.FloatField(default=0.0, verbose_name='Загальна сума всього')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кредитор',
                'verbose_name_plural': 'Кредитори',
                'unique_together': {('name', 'normalized_name')},
            },
        ),
        migrations.CreateModel(
            name='CreditorClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_1st_queue', models.FloatField(blank=True, help_text='Грошові вимоги 1 черги', null=True, verbose_name='Сума 1 черга')),
                ('amount_2nd_queue', models.FloatField(blank=True, help_text='Грошові вимоги 2 черги', null=True, verbose_name='Сума 2 черга')),
                ('amount_3rd_queue', models.FloatField(blank=True, help_text='Грошові вимоги 3 черги', null=True, verbose_name='Сума 3 черга')),
                ('amount_4th_queue', models.FloatField(blank=True, help_text='Грошові вимоги 4 черги', null=True, verbose_name='Сума 4 черга')),
                ('amount_5th_queue', models.FloatField(blank=True, help_text='Грошові вимоги 5 черги', null=True, verbose_name='Сума 5 черга')),
                ('amount_6th_queue', models.FloatField(blank=True, help_text='Грошові вимоги 6 черги', null=True, verbose_name='Сума 6 черга')),
                ('total_amount', models.FloatField(default=0.0, help_text='Сума всіх черг', verbose_name='Загальна сума')),
                ('source_resolution_texts', models.TextField(blank=True, help_text='ID резолютивних частин, з яких витягнуто дані', verbose_name='Джерельні резолютивні частини')),
                ('llm_analysis_result', models.JSONField(blank=True, help_text='Повний результат аналізу мовної моделі', null=True, verbose_name='Результат аналізу LLM')),
                ('confidence_score', models.FloatField(blank=True, help_text='Оцінка від 0 до 1', null=True, verbose_name='Оцінка достовірності')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_claims', to='bankruptcy.bankruptcycase', verbose_name='Справа про банкрутство')),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_claims', to='bankruptcy.creditor', verbose_name='Кредитор')),
            ],
            options={
                'verbose_name': 'Вимога кредитора',
                'verbose_name_plural': 'Вимоги кредиторів',
                'unique_together': {('case', 'creditor')},
            },
        ),
        migrations.CreateModel(
            name='LLMAnalysisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('creditor_extraction', 'Витягування даних кредиторів'), ('test_query', 'Тестовий запит'), ('batch_processing', 'Пакетна обробка')], max_length=50, verbose_name='Тип аналізу')),
                ('status', models.CharField(choices=[('pending', 'Очікування'), ('processing', 'Обробка'), ('completed', 'Завершено'), ('failed', 'Помилка')], default='pending', max_length=20, verbose_name='Статус')),
                ('input_text', models.TextField(verbose_name='Вхідний текст')),
                ('output_text', models.TextField(blank=True, verbose_name='Результат')),
                ('processing_time_seconds', models.FloatField(blank=True, null=True, verbose_name='Час обробки (сек)')),
                ('token_count_input', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість токенів (вхід)')),
                ('token_count_output', models.PositiveIntegerField(blank=True, null=True, verbose_name='Кількість токенів (вихід)')),
                ('error_message', models.TextField(blank=True, verbose_name='Повідомлення про помилку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bankruptcy.bankruptcycase', verbose_name='Справа')),
            ],
            options={
                'verbose_name': 'Лог аналізу LLM',
                'verbose_name_plural': 'Логи аналізу LLM',
                'ordering': ['-created_at'],
            },
        ),
    ]
