# Generated by Django 5.2.6 on 2025-09-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0011_creditor_creditorclaim_llmanalysislog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeduplicationProcessStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases_processed', models.IntegerField(default=0, verbose_name='Справ опрацьовано')),
                ('total_creditors_added', models.IntegerField(default=0, verbose_name='Кредиторів додано')),
                ('total_duplicates_removed', models.IntegerField(default=0, verbose_name='Дублікатів видалено')),
                ('total_claims_updated', models.IntegerField(default=0, verbose_name='Вимог оновлено')),
                ('initial_documents_processed', models.IntegerField(default=0, verbose_name='Вступних частин оброблено')),
                ('full_documents_processed', models.IntegerField(default=0, verbose_name='Повних документів оброблено')),
                ('summary_documents_processed', models.IntegerField(default=0, verbose_name='Підсумкових документів оброблено')),
                ('api_errors', models.IntegerField(default=0, verbose_name='API помилки')),
                ('parsing_errors', models.IntegerField(default=0, verbose_name='Помилки парсингу')),
                ('database_errors', models.IntegerField(default=0, verbose_name='Помилки БД')),
                ('avg_processing_time', models.FloatField(default=0.0, verbose_name='Середній час обробки (сек)')),
                ('last_processed_case_id', models.IntegerField(blank=True, null=True, verbose_name='Останній оброблений ID')),
                ('is_running', models.BooleanField(default=False, verbose_name='Процес запущений')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Останній запуск')),
                ('last_error', models.TextField(blank=True, verbose_name='Остання помилка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Статистика процесу дедуплікації',
                'verbose_name_plural': 'Статистика процесів дедуплікації',
                'db_table': 'bankruptcy_dedup_process_stats',
            },
        ),
        migrations.DeleteModel(
            name='CourtDecision',
        ),
    ]
