# Generated by Django 5.2.6 on 2025-09-16 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0012_deduplicationprocessstats_delete_courtdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeduplicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('creditor_added', 'Кредитор додано'), ('duplicate_removed', 'Дублікат видалено'), ('claim_updated', 'Вимога оновлена'), ('case_processed', 'Справа оброблена')], max_length=20, verbose_name='Тип операції')),
                ('document_type', models.CharField(choices=[('initial', 'Початкова ухвала'), ('full', 'Повний документ'), ('summary', 'Підсумкова ухвала'), ('unknown', 'Невідомий тип')], default='unknown', max_length=10, verbose_name='Тип документа')),
                ('creditor_name', models.CharField(blank=True, max_length=500, verbose_name='Назва кредитора')),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стара сума')),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Нова сума')),
                ('queue_type', models.CharField(blank=True, max_length=20, verbose_name='Тип черги')),
                ('decision_doc_id', models.CharField(blank=True, max_length=50, verbose_name='ID судового рішення')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Час обробки (сек)')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='Додаткові деталі')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Створено')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduplication_logs', to='bankruptcy.bankruptcycase', verbose_name='Справа')),
            ],
            options={
                'verbose_name': 'Лог дедуплікації',
                'verbose_name_plural': 'Логи дедуплікації',
                'db_table': 'bankruptcy_deduplication_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['case', 'operation_type'], name='bankruptcy__case_id_8a8092_idx'), models.Index(fields=['operation_type', 'created_at'], name='bankruptcy__operati_41877d_idx'), models.Index(fields=['document_type', 'created_at'], name='bankruptcy__documen_3483d0_idx')],
            },
        ),
    ]
