# Generated by Django 5.2.6 on 2025-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankruptcy', '0013_deduplicationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedcourtdecision',
            name='database_source',
            field=models.CharField(blank=True, max_length=200, verbose_name='База даних'),
        ),
    ]
